### 1. Load Dataset

In [8]:
import pandas as pd
df = pd.read_excel("Online Retail.xlsx")

### 2. Dataset Shape

In [6]:
df.shape

(541909, 8)

### 3. Columns

In [7]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

### 4. First / Last Rows

In [10]:
df.head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [11]:
df.tail(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

### 5. Data Types

In [12]:
df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

### 6. Statistical Summary

In [16]:
df.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID
count,541909.000000,541909,541909.000000,406829.000000
mean,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 11:34:00,1.250000,13953.000000
50%,3.000000,2011-07-19 17:17:00,2.080000,15152.000000
75%,10.000000,2011-10-19 11:27:00,4.130000,16791.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,218.081158,NaN,96.759853,1713.600303

### 7. Missing Values

In [17]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [21]:
df.isna().mean() * 100

InvoiceNo       0.000000
StockCode       0.000000
Description     0.268311
Quantity        0.000000
InvoiceDate     0.000000
UnitPrice       0.000000
CustomerID     24.926694
Country         0.000000
dtype: float64

### 8. Duplicate Records

In [77]:
f"Duplicate Values: {df.duplicated().sum()}"

'Duplicate Values: 5268'

### 9. Categorical Analysis

#### 1. Country

In [76]:
# Unique Countries
f"There are {df["Country"].nunique()} Unique Countries in Data Set"

'There are 38 Unique Countries in Data Set'

In [75]:
# Frequency Distribution
df["Country"].value_counts()

Country
United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64

#### 2. StockCode

In [74]:
# Unique Stock Codes
f"Total Unique Stock Codes: {df["StockCode"].nunique()}"

'Total Unique Stock Codes: 4070'

In [55]:
f"Total Missing Values in Stock Code Feature: {df["StockCode"].isna().sum()}"

'Total Missing Values in Stock Code Feature: 0'

#### 3. Description

In [49]:
f"Total Unique Descriptions: {df["Description"].nunique()}"

'Total Unique Descriptions: 4223'

In [53]:
f"Total Missing Values in Description Feature: {df["Description"].isna().sum()}"

'Total Missing Values in Description Feature: 1454'

#### 4. InvoiceNo

In [54]:
# Unique Invoice Numbers
f"Total Unique Invoices: {df["InvoiceNo"].nunique()}"

'Total Unique Invoices: 25900'

In [73]:
# Frequency Distribution
df['InvoiceNo'].value_counts()

InvoiceNo
573585     1114
581219      749
581492      731
580729      721
558475      705
           ...
581483        1
581566        1
C581499       1
C536383       1
C536379       1
Name: count, Length: 25900, dtype: int64

In [65]:
cancelled_invoices = df[df['InvoiceNo'].astype(str).str.startswith('C')]
f"Cancelled Orders: {len(cancelled_invoices)}"

'Cancelled Orders: 9288'

#### 5. CustomerID

In [69]:
# Unique Customers
f"Total Unqiue Customers: {df["CustomerID"].nunique()}"

'Total Unqiue Customers: 4372'

In [71]:
# Customer ID Missing Values
f"There are {df["CustomerID"].isna().sum()} missing values in Customer ID"

'There are 135080 missing values in Customer ID'

In [72]:
# Frequency Distribution
df["CustomerID"].value_counts()

CustomerID
17841.0    7983
14911.0    5903
14096.0    5128
12748.0    4642
14606.0    2782
           ...
17986.0       1
13256.0       1
18184.0       1
13747.0       1
15195.0       1
Name: count, Length: 4372, dtype: int64

### 10. Date Range

In [83]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
min_date = df["InvoiceDate"].min()
max_date = df["InvoiceDate"].max()

print(f"Data Starts From: {min_date}")
print(f"Data Ends At:     {max_date}")
print(f"Total Duration:   {max_date - min_date}")
print(f"Invoice Date Feature Data Type: {df["InvoiceDate"].dtypes}")

Data Starts From: 2010-12-01 08:26:00
Data Ends At:     2011-12-09 12:50:00
Total Duration:   373 days 04:24:00
Invoice Date Feature Data Type: datetime64[ns]

### 11. Customer Analysis

#### 1. Total unique customers

In [84]:
f"Total Unqiue Customers: {df["CustomerID"].nunique()}"

'Total Unqiue Customers: 4372'

#### 2. Missing CustomerID

In [86]:
# Customer ID Missing Values
f"There are {df["CustomerID"].isna().sum()} missing values in Customer ID"

'There are 135080 missing values in Customer ID'

#### 3. Customer transaction frequency

In [85]:
# Frequency Distribution
df["CustomerID"].value_counts()

CustomerID
17841.0    7983
14911.0    5903
14096.0    5128
12748.0    4642
14606.0    2782
           ...
17986.0       1
13256.0       1
18184.0       1
13747.0       1
15195.0       1
Name: count, Length: 4372, dtype: int64

In [95]:
# Minimum transactions by a single customer
f"Minimum transactions by a single customer: {df["CustomerID"].value_counts().min()}"

'Minimum transactions by a single customer: 1'

In [94]:
# Maximum transactions by a single customer
f"Maximum transactions by a single customer: {df["CustomerID"].value_counts().max()}"

'Maximum transactions by a single customer: 7983'

In [97]:
# Average (Mean) transactions per customer
f"Average (Mean) transactions per customer: {df["CustomerID"].value_counts().mean().astype(int)}"

'Average (Mean) transactions per customer: 93'

#### 4. Most active customers

In [100]:
print("--- Top 5 Most Active Customers ---")
df['CustomerID'].value_counts().head(5)

--- Top 5 Most Active Customers ---

CustomerID
17841.0    7983
14911.0    5903
14096.0    5128
12748.0    4642
14606.0    2782
Name: count, dtype: int64

#### 5. Customer distribution

In [104]:
customer_tx_counts = df['CustomerID'].value_counts()
distribution = customer_tx_counts.value_counts().sort_index()
print("--- Transaction Frequency Distribution ---")
distribution

--- Transaction Frequency Distribution ---

count
1       79
2       59
3       53
4       55
5       61
        ..
2782     1
4642     1
5128     1
5903     1
7983     1
Name: count, Length: 474, dtype: int64