In [1]:
import pandas as pd
import numpy as np
df = pd.read_excel("Online Retail.xlsx")

### 1. Missing Data Audit

#### Missing Values

In [39]:
missing_values = df.isna().sum()
missing_values

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

#### Missing Values Percentage

In [40]:
missing_values_per = (df.isna().mean() * 100).round(2)
missing_values_per

InvoiceNo       0.00
StockCode       0.00
Description     0.27
Quantity        0.00
InvoiceDate     0.00
UnitPrice       0.00
CustomerID     24.93
Country         0.00
dtype: float64

Column          Missing Count       Missing %
------------------------------------------------
InvoiceNo            0                0.00
StockCode            0                0.00
Description        1454               0.27
Quantity             0                0.00
InvoiceDate          0                0.00
UnitPrice            0                0.00
CustomerID        135080              24.93
Country              0                0.00

### 2. Duplicate Audit

In [16]:
# Dulicates
f" Duplicate Rows: {df.duplicated().sum()}"

' Duplicate Rows: 5268'

In [23]:
f"Percentage of Duplicates: {(df.duplicated().mean() * 100).round(2)}%"

'Percentage of Duplicates: 0.97%'

In [19]:
df[df.duplicated()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
...,...,...,...,...,...,...,...,...
541675,581538,22068,BLACK PIRATE TREASURE CHEST,1,2011-12-09 11:34:00,0.39,14446.0,United Kingdom
541689,581538,23318,BOX OF 6 MINI VINTAGE CRACKERS,1,2011-12-09 11:34:00,2.49,14446.0,United Kingdom
541692,581538,22992,REVOLVER WOODEN RULER,1,2011-12-09 11:34:00,1.95,14446.0,United Kingdom
541699,581538,22694,WICKER STAR,1,2011-12-09 11:34:00,2.10,14446.0,United Kingdom
541701,581538,23343,JUMBO BAG VINTAGE CHRISTMAS,1,2011-12-09 11:34:00,2.08,14446.0,United Kingdom

"It is normal for a single invoice to contain multiple products. Therefore, a repeated invoice number does not necessarily indicate a duplicate transaction."

## 3. Quantity Integrity Audit

#### Quantity Investigation

In [32]:
print(f"Quantity Minimum Value: {df["Quantity"].min()}")
print(f"Quantity Maximum Value: {df["Quantity"].max()}")
print(f"Number of less then 0 Values: {(df["Quantity"] < 0).sum()}")
print(f"Number of equal to 0 Values: {(df["Quantity"] == 0).sum()}")
print(f"Percentage of less then 0 Values: {((df["Quantity"] < 0).mean() * 100).round(2)}%")

Quantity Minimum Value: -80995
Quantity Maximum Value: 80995
Number of less then 0 Values: 10624
Number of equal to 0 Values: 0
Percentage of less then 0 Values: 1.96%

#### Negative Quantity Columns

In [41]:
df[df["Quantity"] < 0].head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom

#### Basic Comparison Between Positive and Negative Quantity

In [59]:
# Positive Quantity
print(" --- Positive Quantity --- ")
print(f"Total Positive Qunatity Rows: {(df["Quantity"] > 0).sum()}")
print(f"Average of Positive Qunatity Rows: {df.loc[df["Quantity"] > 0, "Quantity"].mean()}")
print(f"Maximum Value of Positive Qunatity Rows: {df[df["Quantity"] > 0]["Quantity"].max()}")
print(f"Minimum Value of Positive Qunatity Rows: {df[df["Quantity"] > 0]["Quantity"].min()}")
# Negative Quntity
print(" --- Negative Quantity --- ")
print(f"Total Negative Qunatity Rows: {(df["Quantity"] < 0).sum()}")
print(f"Average of Negative Qunatity Rows: {df.loc[df["Quantity"] < 0, "Quantity"].mean()}")
print(f"Maximum Value of Negative Qunatity Rows: {df[df["Quantity"] < 0]["Quantity"].max()}")
print(f"Minimum Value of Negative Qunatity Rows: {df[df["Quantity"] < 0]["Quantity"].min()}")

 --- Positive Quantity ---
Total Positive Qunatity Rows: 531285
Average of Positive Qunatity Rows: 10.655262241546438
Maximum Value of Positive Qunatity Rows: 80995
Minimum Value of Positive Qunatity Rows: 1
 --- Negative Quantity ---
Total Negative Qunatity Rows: 10624
Average of Negative Qunatity Rows: -45.60721009036145
Maximum Value of Negative Qunatity Rows: -1
Minimum Value of Negative Qunatity Rows: -80995

### 4. UnitPrice Integrity Audit

#### Unit Price Investigation

In [66]:
print(f"Minimum Unit Price: {df["UnitPrice"].min()}")
print(f"Maximum Unit Price: {df["UnitPrice"].max()}")
print(f"Negative Unit Price Rows: {(df["UnitPrice"] < 0).sum()}")
print(f"Equal to 0 Unit Price Rows: {(df["UnitPrice"] == 0).sum()}")
print(f"Percentage of Negative Unit Price Rows: {((df["UnitPrice"] < 0).mean()*100).round(4)} %")
print(f"Percentage of equal to 0 Unit Price Rows: {((df["UnitPrice"] == 0).mean()*100).round(4)} %")
print(f"Positive Unit Price Rows: {(df["UnitPrice"] > 0).sum()}")
print(f"Percentage of Positive Unit Price Rows: {((df["UnitPrice"] > 0).mean()*100).round(4)} %")
print(f"Average of Positive Unit Price: {df.loc[df["UnitPrice"] > 0, "UnitPrice"].mean()}")
print(f"Minimum Value of Positive Unit Price: {df[df["UnitPrice"] > 0]["UnitPrice"].min()}")
print(f"Maximum Value of Positive Unit Price: {df[df["UnitPrice"] > 0]["UnitPrice"].max()}")

Minimum Unit Price: -11062.06
Maximum Unit Price: 38970.0
Negative Unit Price Rows: 2
Equal to 0 Unit Price Rows: 2515
Percentage of Negative Unit Price Rows: 0.0004 %
Percentage of equal to 0 Unit Price Rows: 0.4641 %
Positive Unit Price Rows: 539392
Percentage of Positive Unit Price Rows: 99.5355 %
Average of Positive Unit Price: 4.673647540193402
Minimum Value of Positive Unit Price: 0.001
Maximum Value of Positive Unit Price: 38970.0

In [65]:
df[(df["UnitPrice"] == 0)].head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom

### 5. CustomerID Integrity Audit

In [69]:
f"Total Unique CustomerIDs: {df["CustomerID"].nunique()}"

'Total Unique CustomerIDs: 4372'

In [70]:
f"Total Missing CustomerIDs: {df["CustomerID"].isna().sum()}"

'Total Missing CustomerIDs: 135080'

In [73]:
f"Percentage of Total Missing CustomerIDs: {(df["CustomerID"].isna().mean() * 100).round(2)}%"

'Percentage of Total Missing CustomerIDs: 24.93%'

In [75]:
f"Total Non Missing CustomerIDs: {df["CustomerID"].notna().sum()}"

'Total Non Missing CustomerIDs: 406829'

In [76]:
f"Data Type of Customer ID: {df["CustomerID"].dtypes}"

'Data Type of Customer ID: float64'

In [84]:
# Customer Mutliple Transactions Record
mul_trx = df.groupby("CustomerID")["InvoiceNo"].nunique()
mul_trx

CustomerID
12346.0     2
12347.0     7
12348.0     4
12349.0     1
12350.0     1
           ..
18280.0     1
18281.0     1
18282.0     3
18283.0    16
18287.0     3
Name: InvoiceNo, Length: 4372, dtype: int64

In [87]:
#Top 10 customers by transaction count
mul_trx.sort_values(ascending=False).head(10)

CustomerID
14911.0    248
12748.0    224
17841.0    169
14606.0    128
15311.0    118
13089.0    118
12971.0     89
14527.0     86
13408.0     81
14646.0     77
Name: InvoiceNo, dtype: int64

### 6. StockCode & Description Integrity

#### Stock Code Investigation

In [93]:
f"Number of Unique Stock Codes: {df["StockCode"].nunique()}"

'Number of Unique Stock Codes: 4070'

In [94]:
f"Number of Missing Stock Codes: {df["StockCode"].isna().sum()}"

'Number of Missing Stock Codes: 0'

In [98]:
f"Number of Duplicate Stock Codes: {df["StockCode"].duplicated().sum()}"

'Number of Duplicate Stock Codes: 537839'

In [103]:
# Top 10 Stock Code
df["StockCode"].value_counts().head(10)

StockCode
85123A    2313
22423     2203
85099B    2159
47566     1727
20725     1639
84879     1502
22720     1477
22197     1476
21212     1385
20727     1350
Name: count, dtype: int64

Stock Code Results:
Number of Unique Stock Codes: 4070
Number of Missing Stock Codes: 0
Number of Duplicate Stock Codes: 537839

#### Description Investigation

In [104]:
f"Missing Discription Count: {df["Description"].isna().sum()}"

'Missing Discription Count: 1454'

In [106]:
f"Unique Discription Count: {df["Description"].nunique()}"

'Unique Discription Count: 4223'

In [114]:
# Inconsistent Descriptions
description_consistency = df.groupby("StockCode")["Description"].nunique()
description_consistency[description_consistency > 1]

StockCode
10080           2
10133           2
16008           2
16045           2
20622           2
               ..
90195A          2
90210D          2
DCGS0003        2
DCGS0069        2
gift_0001_20    2
Name: Description, Length: 650, dtype: int64

Description Results:
Missing Description = 1,454
Unique Description = 4,223

### 7. Invoice & Cancellation Audit

In [115]:
f"InvoicNo Feature Data Type: {df["InvoiceNo"].dtypes}"

'InvoicNo Feature Data Type: object'

In [117]:
f"Total Unique Invoices: {df["InvoiceNo"].nunique()}"

'Total Unique Invoices: 25900'

In [118]:
# Invoice Frequencey
df["InvoiceNo"].value_counts()

InvoiceNo
573585     1114
581219      749
581492      731
580729      721
558475      705
           ...
581483        1
581566        1
C581499       1
C536383       1
C536379       1
Name: count, Length: 25900, dtype: int64

In [155]:
# Cancel Orders Invoices
df[df["InvoiceNo"].str.startswith("C",na=False)].head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom

In [125]:
f"Total Cancel Orders: {df["InvoiceNo"].str.startswith("C",na=False).sum()}"

'Total Cancel Orders: 9288'

In [136]:
f"Percentage of Cancel Orders: {(df["InvoiceNo"].str.startswith("C",na=False).mean() * 100).round(2)}%"

'Percentage of Cancel Orders: 1.71%'

In [135]:
cancel_orders =df[df["InvoiceNo"].str.startswith("C",na=False)]
print(f"Cancel Orders Minimum Quantity: {cancel_orders["Quantity"].min()}")
print(f"Cancel Orders Maximum Quantity: {cancel_orders["Quantity"].max()}")
print(f"Cancel Order Negative count: {(cancel_orders["Quantity"] < 0).sum()}")
print(f"Cancel Order Positive count: {(cancel_orders["Quantity"] > 0).sum()}")

Cancel Orders Minimum Quantity: -80995
Cancel Orders Maximum Quantity: -1
Cancel Order Negative count: 9288
Cancel Order Positive count: 0

Results:
- Cancellation rows: 9,288
- Cancellation share: 1.71%
- Cancellation Quantity minimum: -80,995
- Cancellation Quantity maximum: -1
- Negative quantity: 9,288
- Positive quantity: 0

### 8. Cross Column Integrity

##### Quantity ↔ UnitPrice

In [149]:
print(f"Number of rows where quantity is positive and unit price is negative or zero: {((df["Quantity"] > 0 ) & (df["UnitPrice"] <= 0)).sum()}")
print(f"This Condition Percentage: {(((df["Quantity"] > 0 ) & (df["UnitPrice"] <= 0)).mean() * 100).round(2)}%")

Number of rows where quantity is positive and unit price is negative or zero: 1181
This Condition Percentage: 0.22%

In [153]:
df[(df["Quantity"] > 0 ) & (df["UnitPrice"] <= 0)].head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom

In [152]:
print(f"Number of rows where quantity and Unit Price Both Less then Zero: {((df["Quantity"] < 0 ) & (df["UnitPrice"] < 0)).sum()}")
print(f"This Condition Percentage: {(((df["Quantity"] < 0 ) & (df["UnitPrice"] < 0)).mean() * 100).round(2)}%")

Number of rows where quantity and Unit Price Both Less then Zero: 0
This Condition Percentage: 0.0%

In [154]:
df[(df["Quantity"] < 0 ) & (df["UnitPrice"] < 0)].head(5)

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

Results:
Number of rows where quantity is positive and unit price is negative or zero: 1181
Number of rows where quantity and Unit Price Both Less then Zero: 0

# Data Quality Summary

The dataset contains 136,534 missing values, mainly in CustomerID (135,080) and Description (1,454).
There are 5,268 exact duplicate rows that need to be investigated before removal.
Quantity has 10,624 negative values, which are mainly associated with cancellations/returns and should not be removed automatically.
UnitPrice contains 2 negative values and 2,515 zero values. These require further investigation.
CustomerID has 135,080 missing values (24.93%), which may affect customer level analysis.
StockCode has no missing values, but repeated StockCodes are normal because the same product can appear in multiple transactions. Five StockCodes were found with multiple descriptions.
There are 9,288 cancellation rows (1.71%), identified through InvoiceNo values starting with 'C'. All cancellation rows have negative quantities.
There are 1,181 rows where Quantity is positive but UnitPrice is zero or negative, which requires further investigation.
In Phase 3, these issues will be investigated and cleaned according to business rules rather than being automatically removed or modified.