In [2]:
import pandas as pd
import numpy as np
df = pd.read_excel("online_retail_cleaned.xlsx")

In [3]:
df["Revenue"] = df["Quantity"] * df["UnitPrice"]
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
536636,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,10.20
536637,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60
536638,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
536639,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
536640,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85

##### Total Net Revenue

In [8]:
print(f" Total Net Revenue: {df["Revenue"].sum()}")

 Total Net Revenue: 9726006.954

#### Year Wise Revenue Sum

In [14]:
year = df["InvoiceDate"].dt.year
df.groupby(year)["Revenue"].sum()

InvoiceDate
2010     746723.610
2011    8979283.344
Name: Revenue, dtype: float64

#### Month Wise Revene Sum

In [5]:
month = df['InvoiceDate'].dt.month
df.groupby(month)['Revenue'].sum()

InvoiceDate
1      558448.560
2      497026.410
3      682013.980
4      492367.841
5      722094.100
6      689977.230
7      680156.991
8      681386.460
9     1017596.682
10    1069368.230
11    1456145.800
12    1179424.670
Name: Revenue, dtype: float64

#### Year and Month Wise Revenue Sum

In [15]:
year_month = df['InvoiceDate'].dt.strftime('%Y-%m')
year_month_revenue = df.groupby(year_month)['Revenue'].sum().reset_index()
year_month_revenue

   InvoiceDate      Revenue
0      2010-12   746723.610
1      2011-01   558448.560
2      2011-02   497026.410
3      2011-03   682013.980
4      2011-04   492367.841
5      2011-05   722094.100
6      2011-06   689977.230
7      2011-07   680156.991
8      2011-08   681386.460
9      2011-09  1017596.682
10     2011-10  1069368.230
11     2011-11  1456145.800
12     2011-12   432701.060

#### Country Revenue Sum

In [10]:
crs = df.groupby("Country")["Revenue"].sum()
crs

Country
Australia                137009.770
Austria                   10154.320
Bahrain                     548.400
Belgium                   40910.960
Brazil                     1143.600
Canada                     3666.380
Channel Islands           20076.390
Cyprus                    12858.760
Czech Republic              707.720
Denmark                   18768.140
EIRE                     262993.380
European Community         1291.750
Finland                   22326.740
France                   197317.110
Germany                  221509.470
Greece                     4710.520
Hong Kong                  9908.240
Iceland                    4310.000
Israel                     7901.970
Italy                     16890.510
Japan                     35340.620
Lebanon                    1693.880
Lithuania                  1661.060
Malta                      2505.470
Netherlands              284661.540
Norway                    35163.460
Poland                     7213.140
Portugal                  29302.970
RSA                        1002.310
Saudi Arabia                131.170
Singapore                  9120.390
Spain                     54756.030
Sweden                    36585.410
Switzerland               56363.050
USA                        1730.920
United Arab Emirates       1902.280
United Kingdom          8167128.184
Unspecified                4740.940
Name: Revenue, dtype: float64

#### TOP 10 Countries

In [13]:
crs.sort_values(ascending=False).head(10)

Country
United Kingdom    8167128.184
Netherlands        284661.540
EIRE               262993.380
Germany            221509.470
France             197317.110
Australia          137009.770
Switzerland         56363.050
Spain               54756.030
Belgium             40910.960
Sweden              36585.410
Name: Revenue, dtype: float64

#### Revenue Sum according to Invoice Number

In [18]:
inv = df.groupby("InvoiceNo")["Revenue"].sum()
inv

InvoiceNo
536365        139.12
536366         22.20
536367        278.73
536368         70.05
536369         17.85
             ...
C581484   -168469.60
C581490       -32.53
C581499      -224.69
C581568       -54.75
C581569        -7.50
Name: Revenue, Length: 25900, dtype: float64

#### Top 10 Invoices

In [19]:
inv.sort_values(ascending=False).head(10)

InvoiceNo
581483    168469.60
541431     77183.60
574941     52940.94
576365     50653.91
556444     38970.00
567423     31698.16
556917     22775.93
572209     22206.00
567381     22104.80
563614     21880.44
Name: Revenue, dtype: float64

#### Average Invoice

In [20]:
inv.mean()

np.float64(375.521504015444)

#### Average product lines per invoice

In [25]:
total = df["InvoiceNo"].count()
uniq = df["InvoiceNo"].nunique()
avg = total / uniq
avg

np.float64(20.71972972972973)

#### Revenue Reconciliation

In [31]:
rev_sum = df["Revenue"].sum()
inv_sum = inv.sum()
if np.isclose(rev_sum,inv_sum):
    print("Both values are equal")
else:
    print("Both Values are not equal")

Both values are equal

## Business Summary

Total net revenue: 9,726,006.954
Unique invoices: 25,900
Unique customers: 4,372
Average invoice value: approximately 375.52
Highest monthly revenue: November
Highest revenue country: United Kingdom